name: delivery_backoffice
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.2.0
  flutter_dotenv: ^5.0.2
  loading_animation_widget: ^1.2.0+4
  awesome_snackbar_content: ^0.1.2
  dio: ^5.1.2
  validatorless: ^1.2.3
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    
  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800